# Generated by Django 5.0.6 on 2024-05-23 18:53

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('user_link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GamePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('text_picture', models.TextField(blank=True)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('CategoryCheck', models.CharField(blank=True, choices=[('TANK', 'Танки'), ('HEAL', 'Хилы'), ('DD', 'ДД'), ('TRADE', 'Торговцы'), ('GUILDM', 'Гилдмастеры'), ('QUESTGV', 'Квестгиверы'), ('KZ', 'Кузнецы'), ('LETHER', 'Кожевники'), ('Alch', 'Зельевары'), ('MAGIC', 'Мастера заклинаний')], max_length=100)),
                ('link_GameUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RPG_FUNCTIONS.gameuser')),
            ],
        ),
    ]
